# Permalinks
permalink:           pretty

# Setup
title:               Luyuan Kong
tagline:
url:                 https://kassenger.github.io.git
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Luyuan Kong
  url:
  email:             yuqiuyuan2@gmail

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kassenger

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
